name: AWS Secrets Manager

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: eu-north-1
  SECRET_NAME: m508-secrets-lab/dev/database-credentials

jobs:
  retrieve-secret-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Replace with the ARN printed by: terraform output -raw github_actions_role_arn
          role-to-assume: arn:aws:iam::128529977749:role/m508-secrets-lab-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve secret (no long-lived keys)
        run: |
          aws secretsmanager get-secret-value \
            --secret-id "m508-secrets-lab/dev/database-credentials" \
            --query 'SecretString' --output text | jq .

  check-rotation:
    runs-on: ubuntu-latest
    needs: retrieve-secret-oidc
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::128529977749:role/m508-secrets-lab-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Check secret rotation age
        run: |
          chmod +x scripts/check-secret-age.sh
          ./scripts/check-secret-age.sh "m508-secrets-lab/dev/database-credentials" 90
          ./scripts/check-secret-age.sh "m508-secrets-lab/dev/api-keys" 90
